apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-optiplex1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share/proxmox/nginx/data/nginx1
    server: 192.168.0.40
